### ISSUE TITLE
Adonis 4

### ISSUE THREAD

**Issue by thsteinmetz-qo** [helnokaly/adonis-cache#2]
Any chance of getting this updated for Adonis 4?

**Comment by helnokaly** [comment]
An update for Adonis 4 is planned when it is released.

**Comment by markov00** [comment]
Hi, Adonis 4 is now released, do you have any plan for updating the package?

**Comment by helnokaly** [comment]
@markov00 thanks for reminding, working on an update for Adonis 4.

**Comment by helnokaly** [comment]
Updated for Adonis 4 :tada: :balloon:

**Comment by helnokaly** [comment]
@markov00 @thsteinmetz-qo
