### ISSUE TITLE
[ASK] How to clear expired cache

### ISSUE THREAD

**Issue by nautonk** [helnokaly/adonis-cache#4]
Hello @helnokaly ,

I have a problem that my database getting huge size because of cache. I use database CACHE_STORE, how to auto remove / clear expired cache ?

Btw very good repo, keep it up bro.

My english is not good, sorry about that.

regards

**Comment by helnokaly** [comment]
Please update to v0.3.2 (just published) and the database store should garbage collect expired data occasionally.

And if you want to force clear expired data run `await Cache._gc(true);`

Hope this helps. @nautonk

**Comment by nautonk** [comment]
Will do as your suggestion, again thank you so much for your effort 👍 

regards
